query GetMyBinders @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  binders(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    binderName
    isPublic
    createdAt
    updatedAt
  }
}

mutation CreateNewBinder($binderName: String!, $isPublic: Boolean!, $description: String) @auth(level: USER) {
  binder_insert(data: {
    userId_expr: "auth.uid",
    binderName: $binderName,
    isPublic: $isPublic,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time",
    description: $description
  })
}

query GetCardDetails($cardId: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  card(id: $cardId) {
    cardName
    set
    rarity
    imageUrl
    cardType
    cardNumber
    artist
    releaseDate
  }
}

mutation AddCardToUserCollection($cardId: UUID!, $quantity: Int!, $condition: String!, $acquiredAt: Timestamp!, $pricePaid: Float, $notes: String, $isForTrade: Boolean, $isForSale: Boolean) @auth(level: USER) {
  userCard_insert(data: {
    userId_expr: "auth.uid",
    cardId: $cardId,
    quantity: $quantity,
    condition: $condition,
    acquiredAt: $acquiredAt,
    createdAt_expr: "request.time",
    pricePaid: $pricePaid,
    notes: $notes,
    isForTrade: $isForTrade,
    isForSale: $isForSale
  })
}