type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
  bio: String
}

type Card @table {
  cardName: String!
  set: String!
  rarity: String!
  imageUrl: String!
  createdAt: Timestamp!
  cardType: String
  cardNumber: String
  artist: String
  releaseDate: Date
}

type UserCard @table {
  user: User!
  card: Card!
  quantity: Int!
  condition: String!
  acquiredAt: Timestamp!
  createdAt: Timestamp!
  pricePaid: Float
  notes: String
  isForTrade: Boolean
  isForSale: Boolean
}

type Binder @table {
  user: User!
  binderName: String!
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type BinderCard @table(key: ["binder", "userCard"]) {
  binder: Binder!
  userCard: UserCard!
  createdAt: Timestamp!
  positionInBinder: Int
}